matches:
- trigger: ";u"
  replace: "\U0001F64F"

- trigger: ";cs"
  replace: |
    O/
    Siriraj: 
    NIHSS: 
    mRS pre hospital:

    A/
    Susp. Vascular event berulang ec susp SNH dd SH onset 

    P/
    Diagnostik: Cek Lab (DL, FH, faal ginjal, faal hati, CRP), foto toraks, CTA kepala
    Terapi: menunggu hasil CTA
    Monitoring: keluhan, defisit neurologis baru

    I/
    MRS
    Aktivasi code stroke pada

    IVFD NaCl 0.9% 20 tpm
    Pasang infus 18G cubiti kanan

    Cek lab (DL, FH, faal ginjal, faal hati, CRP)
    Foto toraks
    CTA kepala

    Terapi spesifik menunggu hasil CTA

- trigger: ";o/"
  replace: |
    O/
    TD: mmHg
    N: x/menit
    RR: x/menit
    T: C
    SpO2: %

    Klinis neurologis:
    GCS EVM
    Meningeal sign (-)
    Pupil bulat isokor 3 mm / 3 mm
    Reflek cahaya +/+
    Paresis N. Kranialis
    Motorik
    Sensorik
    Otonom
    Refleks fisiologis
    Refleks patologis

- trigger: ";now"
  replace: "{{mytime}}"
  vars:
    - name: mytime
      type: date
      params:
        format: "%d/%m/%Y %H:%M"

- trigger: ";rad"
  replace: "RADIOLOGI:"

- trigger: ";lab"
  replace: "LABORATORIUM:"

- trigger: ";date"
  replace: "{{datetoday}}"
  vars:
    - name: datetoday
      type: date
      params:
        format: "%d/%m/%y"

- trigger: ";time"
  replace: "{{timenow}}"
  vars:
    - name: timenow
      type: date
      params:
        format: "%H:%M"

- trigger: ";yaml"
  replace: |
    - trigger: ""
      replace: ""

- trigger: ";p/"
  replace: |
    P/
    Diagnostik:
    Terapi: 
    Monitoring:

- trigger: ";i/"
  replace: |
    I/
    MRS
    IVFD NaCl 0.9% 20 tpm

- trigger: ";lead"
  replace: "(Leader Neuro)"

- trigger: ";datang"
  replace: |
    Datang:
    Diperiksa:
    BPD:
    Pindah:

- trigger: ";nihss"
  replace: |
    Siriraj:
    NIHSS:
    mRS pre stroke:

- trigger: ";sh"
  replace: |
    ICH score:
    sICH score"

- trigger: ";sah"
  replace: |
    Hunt and Hess:
    Modified Fisher scale: grade

- trigger: ";cekdl"
  replace: "Cek lab (DL, faal hemostasis, faal hati, faal ginjal, glukosa sewaktu, Na, K, Cl)"

- trigger: ";mon"
  replace: "keluhan, defisit neurologis baru"

- trigger: ";stroke"
  replace: |
    Anamnesis singkat di code stroke 
    - identitas
    - onset 
    - last known seen well
    - Gejala : Face, Arm, Speech, Vision (gaze kontra hemiparese umumnya), Afasia, Neglect, gejala posterior 
    - saat aktivitas / tidak
    - Gradual / tidak
    - Faktor resiko RPD
    - RPO
    - indikasi kontra indikasi trombolisis : RPO antikoagulan, hamil, kejang saat onset, tods paralysis, perdarahan aktif, riw perdarahan GIT/Uro 3 minggu, trauma akut, trauma kepala, sakit jantung (IE, diseksi aorta, pericarditis, post MI), stroke 3 bulan, riwayat operasi besar
    - indikasi kontra indikasi trombektomi : mRS 0-1 (modal klinis pasien), gejala LVO (s.d M1)

    Objektif 
    - Siriraj
    - NIHSS
    - mRS pre stroke
    - FAST VAN

    Check list trombolisis, trombek —> jika ada  kontra indikasi dicantumkan

    Setelah code stroke wajib mencantumkan :
    - door to code
    - door to ct 
    - door to needle bila trombolisis
    - door to puncture bila trombek
    - door to cath 
    - door to revaskularization

- trigger: ";omeiv"
  replace: "Omeprazole 40 mg tiap 12 jam IV"

- trigger: ";pctkp"
  replace: "Parasetamol 1000 mg tiap 8 jam IO kp nyeri NPRS >3"